name: 'Create an Organization Repository'
on:
  push:
    branches: # Define example branch names here
      - 'feature/*'
      - 'hotfix/snow-123/*'
  pull_request:

permissions:
  contents: write
  repository-projects: write
  pull-requests: write
  issues: write
  actions: write


description: 'Creates an Organization Repository and adds the Actor as an admin'
branding:
  icon: 'folder-plus'
  color: 'blue'

inputs:
  repo-name: 'Test Repo'
    description: 'What is the name of the repository?'
    required: true
    default: ''
  org-admin-token:
    description: 'Organization admin token with admin:org scope'
    required: true
    default: ''
outputs:
  repo-url: # change this as needed
    description: 'URL of the created repository'
runs:
  using: 'node12'
  main: 'dist/index.js'
